Got rid of println.
Can't test compilation because of
```
C:\Users\Mark\AppData\Local\Temp\arduino_build_537843\sketch\sciwing.cpp:30:33:
fatal error: src/TLC5955/TLC5955.h: No such file or directory

compilation terminated.

Error compiling for board Teensy 3.2 / 3.1.
```